version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-production}
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge 