services:
  - type: web
    name: newssnapaiserver
    env: node
    buildCommand: npm ci && npm run build
    startCommand: cd /opt/render/project/src && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
