version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.15
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build
          command: npm run build
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage

  deploy:
    docker:
      - image: cimg/node:18.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t $DOCKER_USERNAME/newssnapai-server:${CIRCLE_SHA1} .
            docker tag $DOCKER_USERNAME/newssnapai-server:${CIRCLE_SHA1} $DOCKER_USERNAME/newssnapai-server:latest
            docker push $DOCKER_USERNAME/newssnapai-server:${CIRCLE_SHA1}
            docker push $DOCKER_USERNAME/newssnapai-server:latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
